import unittest
from secops_defense.rule_generator import RuleGenerator, generate_firewall_from_intel


class TestRuleGenerator(unittest.TestCase):
    def setUp(self):
        self.gen = RuleGenerator()

    def test_init_default_author(self):
        self.assertEqual(self.gen.author, "SecOps-AI")

    def test_init_custom_author(self):
        gen = RuleGenerator(author="CustomBot")
        self.assertEqual(gen.author, "CustomBot")

    def test_nftables_empty_ips(self):
        result = self.gen.generate_nftables_rules([])
        self.assertEqual(result, "")

    def test_nftables_single_ip(self):
        result = self.gen.generate_nftables_rules(["1.2.3.4"])
        self.assertIn("1.2.3.4", result)
        self.assertIn("secops_ai_blocklist", result)
        self.assertIn("table inet filter", result)

    def test_nftables_multiple_ips(self):
        result = self.gen.generate_nftables_rules(["1.2.3.4", "5.6.7.8", "9.10.11.12"])
        self.assertIn("1.2.3.4", result)
        self.assertIn("5.6.7.8", result)
        self.assertIn("9.10.11.12", result)

    def test_modsecurity_empty(self):
        result = self.gen.generate_modsecurity_rules([])
        self.assertIn("Generated by", result)

    def test_modsecurity_payload_match(self):
        anomalies = [
            {"type": "payload_match", "pattern": "<script>.*</script>"},
            {"type": "payload_match", "pattern": "union\\s+select"},
        ]
        result = self.gen.generate_modsecurity_rules(anomalies)
        self.assertIn("SecRule", result)
        self.assertIn("9000000", result)
        self.assertIn("9000001", result)
        self.assertIn("<script>.*</script>", result)

    def test_modsecurity_ignores_non_payload_match(self):
        anomalies = [{"type": "other", "pattern": "test"}]
        result = self.gen.generate_modsecurity_rules(anomalies)
        self.assertNotIn("SecRule", result)

    def test_modsecurity_ignores_missing_pattern(self):
        anomalies = [{"type": "payload_match"}]
        result = self.gen.generate_modsecurity_rules(anomalies)
        self.assertNotIn("SecRule", result)


class TestGenerateFirewallFromIntel(unittest.TestCase):
    def test_with_ips(self):
        result = generate_firewall_from_intel(["1.2.3.4", "5.6.7.8"])
        self.assertIn("1.2.3.4", result)
        self.assertIn("5.6.7.8", result)

    def test_empty(self):
        result = generate_firewall_from_intel([])
        self.assertEqual(result, "")


if __name__ == "__main__":
    unittest.main()
