"""Auto-generation Pipeline for WAF and Firewall Rules"""

import hashlib
from datetime import datetime
from typing import List, Dict

class RuleGenerator:
    def __init__(self, author="SecOps-AI"):
        self.author = author

    def generate_nftables_rules(self, malicious_ips: List[str]) -> str:
        """Generate nftables rules to block malicious IPs."""
        if not malicious_ips:
            return ""

        elements = ", ".join(malicious_ips)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        rule = f"""# Generated by {self.author} at {timestamp}
# Context: AI Auto-generated blocklist
table inet filter {{
    set secops_ai_blocklist {{
        type ipv4_addr
        elements = {{ {elements} }}
    }}

    chain input {{
        type filter hook input priority 0; policy accept;
        ip saddr @secops_ai_blocklist drop comment "AI Auto-generated Block"
    }}
}}
"""
        return rule

    def generate_modsecurity_rules(self, anomalies: List[Dict]) -> str:
        """
        Generate ModSecurity WAF rules from anomaly descriptions or payload patterns.
        Expected anomaly format: {"type": "payload_match", "pattern": "<malicious_regex>"}
        """
        rules = []
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        rules.append(f"# Generated by {self.author} at {timestamp}")
        
        base_id = 9000000
        
        for idx, anomaly in enumerate(anomalies):
            if anomaly.get("type") == "payload_match" and "pattern" in anomaly:
                pattern = anomaly["pattern"]
                rule_id = base_id + idx
                # Basic ModSecurity rule template
                rule = (
                    f"SecRule ARGS|REQUEST_HEADERS \"@rx {pattern}\" \\\n"
                    f"    \"id:{rule_id},\\\n"
                    f"    phase:2,\\\n"
                    f"    deny,\\\n"
                    f"    status:403,\\\n"
                    f"    log,\\\n"
                    f"    msg:'AI Auto-generated WAF Rule: Suspected payload match'\"\n"
                )
                rules.append(rule)
                
        return "\n".join(rules)

def generate_firewall_from_intel(intel_data: List[str]) -> str:
    """Helper function to process threat intel feeds directly into firewall rules."""
    generator = RuleGenerator()
    return generator.generate_nftables_rules(intel_data)
